lib/Smtpapi/Header.php
The method is being called [here](https://github.com/sendgrid/sendgrid-php/blob/master/lib/SendGrid/Email.php#L244)
=> Added missing setCategory method

lib/Smtpapi/Header.php
The "batch_id" parameter was missing.
👍
=> batch_id header added

TROUBLESHOOTING.md
=> Added TROUBLESHOOTING + Debug Info

CONTRIBUTING.md
Fix #36. 
But there are no USE_CASES, USAGE files ini this repo. And also README doesn't have table of content section.
=> More seo friendly links

README.md
Add table of content to README with links #40.
@mbernier edit: fix #40
=> Add table of content to README

.github/ISSUE_TEMPLATE
=> add ISSUE_TEMPLATE

README.md
=> Add Packagist to README.md

USAGE.md
Added a [USAGE.md] file as per #41.
It says basic in the issue, and I'm sure more can be added over time.
Anything that I should change or update, let me know.
[USAGE.md]: https://github.com/pxgamer/smtpapi-php/blob/feature/usage_file/USAGE.md
=> Add a USAGE.md file

.gitignore
Composer.lock should be committed:
https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control
=> Update .gitignore (commit composer.lock)

composer.lock
This is the first composer.lock commit since pull request https://github.com/sendgrid/smtpapi-php/pull/60 was accepted. This might conflict with existing composer.lock on contributor's local repo (git pull will most likely fail), as different contributors might have different composer.lock (since they were previously ignored by .gitignore). Discarding the local file (rm composer.lock) and pulling (git pull) is an easy solution. No breaking changes are expected.
=> First composer.lock commit

.env_sample
=> Add a .env_sample file

USAGE.md
=> Added missing '>' in SetTos usage example.

test/Smtpapi/Header.php
=> Add license date range test

test/RepoFilesExists.php, test/phpunit.xml.dist
Add unit test to ensure specific file exist in the repository.
=> Add unittest to check that specific files exist in repo

CONTRIBUTING.md, README.md
Closes #80
- Adds Code Reviews to CONTRIBUTING.md
=> Add Code Reviews to CONTRIBUTING.md

.travis.yml, composer.json, composer.lock, test/Smtpapi/Header.php, test/phpunit.xml.dist
Fixes #91 
- Updates PHPUnit to the latest version which supports PHP 5.6
- The tests were *not* passing *or* running in CI. Before the broken file check test was added, the tests were not running. The build passed but if you look at the build log it says "No tests executed!" This fixes that. I ran 27 tests.
- Fixed one test that had the wrong reference to a file.
Passing tests on CI:
=> Update PHPUnit and establish passing builds

CONTRIBUTING.md
Fixes #80 
- Adds a section to the CONTRIBITING.md for code reviews
- Links to section in table of contents
If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.
=> docs: Add Code Reviews Section to README

use_cases/README.md
- Adds a use cases directory and a README.md file for it. Closes #83 
If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.
=> docs: Add use cases directory

lib/Smtpapi/Header.php, test/Smtpapi/Header.php, test/phpunit.xml.dist, test/smtpapi_test_strings.json
Fixes #7
- Adding quotes around the sender name
- Incorporated some test fixes from my other PR #92 in order to get a passing build.
=> Adding Quotes around "To" Name

examples/example.php
Checked the validity of old URL's and replaced two of them with the latest ones, otherwise they will lead to ugly redirection.
- 
- 
If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.
=> docs: update old URL's with the latest ones

CONTRIBUTING.md, README.md, USAGE.md, composer.json
=> chore: add Twilio branding

.github/workflows/test-and-deploy.yml, README.md
Added a deploy job to the test and deploy GitHub Action workflow that creates a new GitHub release when run for tags. Updated build status badge and Slack notification to cover deployments by the workflow.
=> chore: add deploy job to test and deploy gh workflow
